### POST
POST http://localhost:3000/api/v1/products/
Content-Type: application/json

{
    "name": "product 4",
    "description": "this is product 4",
    "richDescription": "product 4 rich description",
    "image": "product 4 image",
    "brand": "brand product 4",
    "price": 30,
    "category": "61c2101d15e73b1a9a228c47",
    "countInStock": 26,
    "rating": 14,
    "numReviews": 22,
    "isFeatured": false
}

### LOGIN
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "email": "huy3@huy.com",
    "password": "1234"
}


### POST users
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json

{
    "name": "huy5",
    "email": "huy5@huy.com",
    "password": "1234",
    "phone": "12567890",
    "isAdmin": true,
    "apartment": "Apartment 0134",
    "zip": "1021",
    "city": "Hanoi",
    "country": "Vietnam",
    "street": "Street 1011"
}

### UPDATE product
PUT http://localhost:3000/api/v1/products/61c1f5cc760f5364af2df2f4
Content-Type: application/json

{
    "name": "product 2",
    "description": "this is product 2",
    "richDescription": "product 2 rich description",
    "image": "product 2 image",
    "brand": "brand product 2",
    "price": 30,
    "category": "61c2102c15e73b1a9a228c49",
    "countInStock": 14,
    "rating": 1,
    "numReviews": 3,
    "isFeatured": true
}

### GET all user
GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWM2OGUyNDgwZDYyYjE5NWJmZTBmODQiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDA0MjM0MjksImV4cCI6MTY0MDUwOTgyOX0.Dn6lLH46TACC5jVVX6vd3VL3Gfqiwph_R7XjopM_k68

### GET user by ID
GET http://localhost:3000/api/v1/users/61c68e2480d62b195bfe0f84


### GET
GET http://localhost:3000/api/v1/products?categories=61c2102c15e73b1a9a228c49

### GET ALL products
GET http://localhost:3000/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWM2OGUyNDgwZDYyYjE5NWJmZTBmODQiLCJpYXQiOjE2NDA0MjA2NTYsImV4cCI6MTY0MDUwNzA1Nn0.cd_LYVl-PGe3o-3TP5K98-ghF1Dx-5U6T-0qwgxwi9E


### COUNT product
GET http://localhost:3000/api/v1/products/get/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWM2OGUyNDgwZDYyYjE5NWJmZTBmODQiLCJpYXQiOjE2NDA0MjA2NTYsImV4cCI6MTY0MDUwNzA1Nn0.cd_LYVl-PGe3o-3TP5K98-ghF1Dx-5U6T-0qwgxwi9E

### COUNT users
GET http://localhost:3000/api/v1/users/get/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWM2OGUyNDgwZDYyYjE5NWJmZTBmODQiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDA0MjM3MTgsImV4cCI6MTY0MDUxMDExOH0.WCPyMrk0mEFdYrDKvKVQAfdprl5TONzuDFEFbbvZpOw

### COUNT featured
GET http://localhost:3000/api/v1/products/get/featured/2


### GET by id
GET http://localhost:3000/api/v1/products/61c5e58c12271a3f002c9f02

### POST category
POST http://localhost:3000/api/v1/categories/
Content-Type: application/json

{
    "name": "latop",
    "icon": "laptop-icon",
    "color": "#777"
}

### UPDATE category
PUT http://localhost:3000/api/v1/categories/61c209f95ffa318b38a07dec
Content-Type: application/json

{
    "name": "beauty",
    "icon": "beauty-icon",
    "color": "#878"
}

### GET Category
GET http://localhost:3000/api/v1/categories

### GET Category by ID
GET http://localhost:3000/api/v1/categories/61c209f95ffa318b38a07dec

### DELETE Category
DELETE http://localhost:3000/api/v1/categories/

### DELETE product
DELETE http://localhost:3000/api/v1/products/61c1f610760f5364af2df2f6

### DELETE user by Id
DELETE http://localhost:3000/api/v1/users/61c68c7dcf9ab7152254f36a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWM2OGUyNDgwZDYyYjE5NWJmZTBmODQiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NDA0MjM0MjksImV4cCI6MTY0MDUwOTgyOX0.Dn6lLH46TACC5jVVX6vd3VL3Gfqiwph_R7XjopM_k68
